version: '3.8'

networks:
  proxy:
    external:
      name: proxy-manager_default
  internal:
    driver: bridge

services:

  # Serviço de visualização e dashboards para monitoramento
  # Interface acessível em http://localhost:3000
  # Credenciais padrão: admin/admin
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy

  # Serviço de coleta de métricas para monitoramento
  # Interface acessível em http://localhost:9090
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/caiosimioni/desktop/gwyn-homelab/services/monitoramento/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal

  # Serviço de coleta e consulta de logs
  # Usado em conjunto com o Grafana para visualização de logs
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /home/caiosimioni/desktop/gwyn-homelab/services/monitoramento/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - internal

  # Exporta métricas do sistema operacional do host
  # Usado pelo Prometheus para monitorar o host
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - internal

  # Exporta métricas de containers Docker
  # Usado pelo Prometheus para monitorar containers
  # Interface acessível em http://localhost:8080
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal

volumes:
  grafana_data:
  prometheus_config:
    driver: local
  loki_config:
    driver: local