# ------------------------------------------------------------------------
# ./loki/loki-config.yml
# Autor Caio Simioni
#
# Arquivo de configuração do Loki
#
# Uso:
#   Aponte o arquivo no volume do container Loki no docker-compose.yml
#
#   volumes:
#     - ./loki/loki-config.yml:/etc/loki/local-config.yaml
#
# Descrição:
#   Configura o Loki para armazenar logs em disco e indexá-los para consultas.
#   Define limites de consulta e parâmetros de desempenho.

# Configurações gerais de autenticação e servidor
auth_enabled: false                      # Desativa autenticação (útil para ambientes locais)
server:
  http_listen_port: 3100                 # Porta HTTP para API do Loki
  grpc_listen_port: 9096                 # Porta gRPC para comunicação interna
  log_level: info                        # Nível de log do servidor

# Configurações comuns para armazenamento e replicação
common:
  path_prefix: /loki                     # Prefixo do caminho base para armazenamento
  storage:
    filesystem:
      chunks_directory: /loki/chunks      # Diretório para chunks de log
      rules_directory: /loki/rules        # Diretório para regras
  replication_factor: 1                  # Fator de replicação (1 para ambientes locais)
  ring:
    kvstore:
      store: inmemory                   # Armazena dados do anel em memória

# Configurações de armazenamento
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index  # Diretório ativo para índices
    cache_location: /loki/boltdb-cache   # Localização do cache do boltdb
  filesystem:
    directory: /loki/chunks              # Diretório para armazenamento de arquivos

# Configurações de esquema para indexação
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_                  # Prefixo para índices
        period: 24h                     # Período de rotação dos índices

# Configurações de limites para consultas e ingestão
limits_config:
  reject_old_samples: true              # Rejeita amostras antigas
  reject_old_samples_max_age: 168h      # Idade máxima para amostras antigas
  allow_structured_metadata: false      # Desativa metadados estruturados
